export const API_CONFIG = {
  BASE_URL: "https://salemanagementbackend.onrender.com/api",
  TEST_SIGNIN_URL: "/auth/testsignin",
  SIGNIN_URL: "/auth/signin",
  SIGNUP_URL: "/auth/register",
  GET_PROFILE: "/member/getprofile",
  UPDATE_PROFILE: "/member/profile",
  UPDATE_PASSWORD: "/member/updatepassword",
  USER_PRODUCTS: "/member/products",
  ADD_PRODUCTS: "/member/createproduct",
  GET_PRODUCT_BY_ID: "/member/getproduct",
  UPDATE_PRODUCT: "/member/updateproduct",
  GET_INVOICES: "/member/getinvoices",
  CREATE_INVOICES: "/member/createinvoice",
  CREATE_INVOICES_WITH_ITEMS: "/member/createinvoicewithitems",
  GET_PRODUCT_BY_SKU: "/member/getproductbysku",
  GET_DASHBOARD_DATA: "/member/dashboarddata",

  GET_LEAD_TYPE: "/member/getAllLeadType",
  ADD_LEAD_TYPE: "/member/addLeadType",
  UPDATE_LEAD_TYPE: "member/updateLeadType",
  DELETE_LEAD_TYPE: "/member/deleteLeadType",

  GET_LEAD_SOURCE: "/member/getAllLeadSource",
  ADD_LEAD_SOURCE: "/member/addLeadSource",
  UPDATE_LEAD_SOURCE: "member/updateLeadSource",
  DELETE_LEAD_SOURCE: "/member/deleteLeadSource",

  GET_ORGANISATION_PROFILE: "/member/getOrganisationProfile",
  UPDATE_ORGANISATION_PROFILE: "/member/updateOrganisationProfile",
  DELETE_ORGANISATION_PROFILE: "/member/deleteOrganisationProfile",

  ADD_USER_ORGANISATION: "/auth/addUserOrganisation",
  UPDATE_USER_ORGANISATION: "member/updateUserOrganisation",
  GET_USER_ORGANISATION: "/member/getUserOrganisation",
  GET_ALL_USER_ORGANISATION: "/member/getAllUserOrganisation",
  INVITE_USER: "/member/inviteUser",

  ADD_LEAD: "/member/addLead",
  GET_LEAD_BY_USER: "/member/getLeadByUserId",
  GET_ALL_LEAD_BY_ORGANISATION: "/member/getAllLeadsByOrganisation",
  UPDATE_LEAD: "/member/updateLead",

  GET_LEAD_MESSAGES: "/member/getLeadMessages",
  ADD_LEAD_MESSAGE: "/member/addLeadMessage",

  GET_ALL_CLIENT_BY_ORGANISATION: "/member/getAllClientsByOrganisation",
  GET_CLIENT_BY_ID: "/member/getClientById",
  ADD_CLIENT: "/member/addClient",
  UPDATE_CLIENT: "/member/updateClient",

  GET_ALL_PROPOSALS_BY_ORGANISATION: "/member/getAllProposalForOrganisation",
  GET_ALL_PROPOSALS_BY_USER: "/member/getAllProposalForUser",
  ADD_PROPOSAL: "/member/addProposal",
  UPDATE_PROPOSAL: "/member/updateProposal",
};
